services:
  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?}
      MARIADB_DATABASE: ${DB_NAME:-ragnarok}
      MARIADB_USER: ${DB_USER:-ragnarok}
      MARIADB_PASSWORD: ${DB_PASSWORD:?}
    ports:
      - '3306:3306'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql

  rathena:
    image: ghcr.io/kbokleber/ro-rathena:latest
    depends_on:
      - db
    ports:
      - "6900:6900"
      - "6121:6121"
      - "5121:5121"
    environment:
      DB_NAME: ${DB_NAME:-ragnarok}
      DB_USER: ${DB_USER:-ragnarok}
      DB_PASSWORD: ${DB_PASSWORD:?}
      DB_HOST: db
      DB_PORT: 3306
      PUBLIC_IP: ${PUBLIC_IP:?}
    volumes:
      - './rathena/conf:/rathena/conf'
      - './rathena/log:/rathena/log'

volumes:
  db_data:
